return {
	-- "nvim-neo-tree/neo-tree.nvim",
	-- branch = "v3.x",
	-- dependencies = {
	-- 	"nvim-lua/plenary.nvim",
	-- 	"MunifTanjim/nui.nvim",
	-- },
	-- config = function()
	-- 	require("neo-tree").setup({
	-- 		default_component_configs = {
	-- 			icon = {
	-- 				enabled = false,
	-- 			},
	-- 			modified = {
	-- 				symbol = "",
	-- 			},
	-- 			git_status = {
	-- 				symbols = {
	-- 					added = "",
	-- 					modified = "",
	-- 					deleted = "",
	-- 					renamed = "",
	-- 					untracked = "",
	-- 					ignored = "",
	-- 					unstaged = "",
	-- 					staged = "",
	-- 					conflict = "",
	-- 				},
	-- 			},
	-- 		},
	--
	-- 		filesystem = {
	-- 			filtered_items = {
	-- 				hide_dotfiles = false,
	-- 				hide_gitignored = false,
	-- 			},
	-- 		},
	--
	-- 		renderers = {
	-- 			file = {
	-- 				{ "indent" },
	-- 				{ "name" },
	-- 			},
	-- 			directory = {
	-- 				{ "indent" },
	-- 				{ "name" },
	-- 			},
	-- 		},
	--
	-- 		window = {
	-- 			mappings = {
	-- 				["l"] = "open",
	-- 				["h"] = "close_node",
	-- 				["<space>"] = "toggle_node",
	-- 				["/"] = "fuzzy_finder",
	-- 			},
	-- 		},
	-- 	})
	-- end,
}
